name: NuGet Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:
      - name: Build solution and generate NuGet package
        run: |
          cd <project>
          dotnet pack -c Release -o out
      
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: EventBus.Core
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: EventBus.Core
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: EventBus.RabbitMQ
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: EventBus.RabbitMQ
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
